### ISSUE TITLE
Icon cdn path changed

### ISSUE THREAD

**Issue by MulverineX** [Juby210/text-react#7]
![image](https://user-images.githubusercontent.com/12068027/132136287-2cdcdd4f-5db8-4df6-b3a0-f1ef172699e9.png)

**Comment by Juby210** [comment]
that's weird but I still have correct icon and https://canary.discord.com/assets/bbe8ae762f831966587a35010ed46f67.svg points to valid icon.

**Comment by MulverineX** [comment]
Turns out it's actually caused by a theme by someone who refuses to keep it in its lane.
